#!/bin/bash
set -e

echo "Copying the patched Sileo to the Applications folder..."
/bin/cp -r /tmp/sileofiles.tmp/Applications/Sileo.app /Applications/Sileo.app

echo "Cleaning up..."
/bin/rm -rf /tmp/sileo.deb /tmp/sileofiles.tmp

echo "Setting permissions..."
/bin/chmod -R 755 /Applications/Sileo.app
/bin/chmod 4755 /Applications/Sileo.app/giveMeRoot

echo "Refreshing icon cache..."
/usr/bin/uicache

exit 0